version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Ensure Node.js version is compatible with your React setup
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Artifacts are ready for deployment."
artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
