version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install."
  build:
    commands:
      - echo "No build process required."
  post_build:
    commands:
      - echo "Preparing artifacts for deployment."
artifacts:
  files:
    - 'frontend/**/*'

